### ISSUE TITLE
pytest errors

### ISSUE THREAD

**Issue by JeanMarie-TTS** [18F/django-template#4]
``1. Had to install npm to get some tests to pass. We should mention this in the README. I guess we need to install docker too.
2. Should touch __init__.py in the tests directory. This lets us run pytest directly.
3. I get the following errors when I run all the tests:
`================================ short test summary info ================================
ERROR tests/test_integration.py::test_docker_compose_build - KeyError: 'circleci'
ERROR tests/test_integration.py::test_docker_tests - KeyError: 'circleci'
ERROR tests/test_integration.py::test_page_load - KeyError: 'circleci'
ERROR tests/test_integration.py::test_nonexistent_page - KeyError: 'circleci'
`

**Comment by JeanMarie-TTS** [comment]
BTW, I don't have permission to create a branch and submit a pull request.

**Comment by JeanMarie-TTS** [comment]
copying @neilmb

**Comment by neilmb** [comment]
Somewhere along the way we fixed this without closing this issue:

```$ pipenv run pytest
============================================= test session starts =============================================
platform darwin -- Python 3.10.3, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/neildmartinsenburrell/src/django-template
plugins: click-1.1.0
collected 30 items

tests/test_command.py ..                                                                                [  6%]
tests/test_creator.py .......                                                                           [ 30%]
tests/test_integration.py ....                                                                          [ 43%]
tests/test_template.py .................                                                                [100%]

======================================= 30 passed in 271.80s (0:04:31) ========================================
```
